#!/usr/bin/env python3
import argparse
import os
import re
import sys
import tempfile
from pathlib import Path

ENV_NAME_PATTERN = re.compile(r"[A-Za-z_][A-Za-z0-9_]*")
LOCAL_OVERRIDE_NAMES = (
    "POSTGRES_HOST",
    "POSTGRES_PORT",
    "POSTGRES_USER",
    "POSTGRES_PASSWORD",
    "POSTGRES_DB",
    "REDIS_URL",
    "CELERY_BROKER_URL",
    "CELERY_RESULT_BACKEND",
    "SECRET_KEY",
)
LOCAL_APPLICATION_DEFAULT_NAMES = ("PRODUCT_IMPORT_MAX_FILE_SIZE",)
R2_REQUIRED_NAMES = (
    "R2_ENDPOINT_URL",
    "R2_BUCKET",
    "R2_ACCESS_KEY",
    "R2_SECRET_KEY",
    "R2_PUBLIC_BASE_URL",
)
SAFETY_OVERRIDES = {
    "APP_ENV": "development",
    "MEDIA_ORPHAN_CLEANUP_ENABLED": "false",
    "MEDIA_ORPHAN_CLEANUP_DRY_RUN": "true",
}


class ConfigError(RuntimeError):
    pass


def parse_env_file(path: Path) -> tuple[dict[str, str], list[str]]:
    if not path.is_file():
        raise ConfigError(f"配置文件不存在：{path}")

    values: dict[str, str] = {}
    order: list[str] = []
    for line_number, raw_line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("export "):
            line = line[7:].lstrip()
        if "=" not in line:
            raise ConfigError(f"{path} 第 {line_number} 行不是有效的 KEY=VALUE 配置")

        name, value = line.split("=", 1)
        name = name.strip()
        if not ENV_NAME_PATTERN.fullmatch(name):
            raise ConfigError(f"{path} 第 {line_number} 行的变量名无效")
        if name in values:
            raise ConfigError(f"{path} 中存在重复变量：{name}")
        values[name] = value.strip()
        order.append(name)
    return values, order


def normalized_value(value: str) -> str:
    normalized = value.strip()
    if len(normalized) >= 2 and normalized[0] == normalized[-1] and normalized[0] in {'"', "'"}:
        return normalized[1:-1].strip()
    return normalized


def require_values(values: dict[str, str], names: tuple[str, ...], source: str) -> None:
    missing_names = [name for name in names if not normalized_value(values.get(name, ""))]
    if missing_names:
        raise ConfigError(f"{source} 缺少必要变量：{', '.join(missing_names)}")


def build_local_config(
    server_values: dict[str, str],
    server_order: list[str],
    local_values: dict[str, str],
) -> tuple[dict[str, str], list[str]]:
    if normalized_value(server_values.get("STORAGE_DRIVER", "")).lower() != "r2":
        raise ConfigError("服务器配置必须设置 STORAGE_DRIVER=r2")
    require_values(server_values, R2_REQUIRED_NAMES, "服务器配置")
    require_values(local_values, LOCAL_OVERRIDE_NAMES, "本地配置")

    merged_values = {
        name: value for name, value in server_values.items() if name not in LOCAL_APPLICATION_DEFAULT_NAMES
    }
    merged_values.update({name: local_values[name] for name in LOCAL_OVERRIDE_NAMES})
    merged_values.update(SAFETY_OVERRIDES)

    merged_order = [name for name in server_order if name not in LOCAL_APPLICATION_DEFAULT_NAMES]
    for name in (*LOCAL_OVERRIDE_NAMES, *SAFETY_OVERRIDES):
        if name not in merged_order:
            merged_order.append(name)
    return merged_values, merged_order


def write_env_file(path: Path, values: dict[str, str], order: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary_path = None
    try:
        with tempfile.NamedTemporaryFile(
            "w",
            encoding="utf-8",
            dir=path.parent,
            prefix=f".{path.name}.",
            delete=False,
        ) as output:
            temporary_path = Path(output.name)
            output.write("# Generated by scripts/build_local_docker_env.py. Do not edit or commit.\n")
            for name in order:
                output.write(f"{name}={values[name]}\n")
        os.chmod(temporary_path, 0o600)
        os.replace(temporary_path, path)
    except Exception:
        if temporary_path and temporary_path.exists():
            temporary_path.unlink()
        raise


def main() -> int:
    parser = argparse.ArgumentParser(description="生成本地 Docker 使用的服务器业务配置与本地基础设施合并文件")
    parser.add_argument("--server-env", type=Path, default=Path(".env.server-docker"))
    parser.add_argument("--local-env", type=Path, default=Path(".env.docker"))
    parser.add_argument("--output", type=Path, default=Path(".env.local-docker"))
    args = parser.parse_args()

    try:
        server_values, server_order = parse_env_file(args.server_env)
        local_values, _ = parse_env_file(args.local_env)
        merged_values, merged_order = build_local_config(server_values, server_order, local_values)
        write_env_file(args.output, merged_values, merged_order)
    except (ConfigError, OSError) as exc:
        print(f"生成失败：{exc}", file=sys.stderr)
        return 1

    print(f"已生成 {args.output}：使用服务器 R2/业务配置、本地基础设施配置，并启用本地环境安全覆盖")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
